name: news_feather
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.0
  html: ^0.15.4
  flutter_carousel_widget: ^2.2.0  # New package
  image_picker: ^1.0.7
  firebase_storage: ^11.6.0
  firebase_auth: ^4.19.0
  google_sign_in: ^6.2.1        # For Google Sign-In
  # For Apple Sign-In
  # Removed: twitter_login: ^4.2.3
  # Removed: flutter_facebook_auth: ^6.0.4
  firebase_app_check: ^0.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true